"""baseline schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-29 20:13:37.559759
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('ip_addr', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('os_info', sa.String(length=256), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rca_feedback_weights',
    sa.Column('candidate_id', sa.String(length=128), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('weight_delta', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('topology_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nodes_json', sa.JSON(), nullable=True),
    sa.Column('edges_json', sa.JSON(), nullable=True),
    sa.Column('source_versions_json', sa.JSON(), nullable=True),
    sa.Column('confidence_summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('cpu_percent', sa.Integer(), nullable=True),
    sa.Column('rss_mb', sa.Integer(), nullable=True),
    sa.Column('read_kb_s', sa.Integer(), nullable=True),
    sa.Column('write_kb_s', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_metric_snapshots_agent_id'), 'agent_metric_snapshots', ['agent_id'], unique=False)
    op.create_table('diagnosis_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('normalized_intent_json', sa.JSON(), nullable=True),
    sa.Column('target_scope_json', sa.JSON(), nullable=True),
    sa.Column('requested_time_range_json', sa.JSON(), nullable=True),
    sa.Column('effective_time_range_json', sa.JSON(), nullable=True),
    sa.Column('topology_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('baseline_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_profile', sa.String(length=64), nullable=False),
    sa.Column('risk_budget_json', sa.JSON(), nullable=True),
    sa.Column('resource_budget_json', sa.JSON(), nullable=True),
    sa.Column('budget_used_json', sa.JSON(), nullable=True),
    sa.Column('hypothesis_graph_json', sa.JSON(), nullable=True),
    sa.Column('evaluation_oracle_json', sa.JSON(), nullable=True),
    sa.Column('child_task_ids_json', sa.JSON(), nullable=True),
    sa.Column('conclusion_versions_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('planner_version', sa.String(length=64), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topology_snapshot_id'], ['topology_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_sessions_topology_snapshot_id'), 'diagnosis_sessions', ['topology_snapshot_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('target_pid', sa.Integer(), nullable=False),
    sa.Column('collector_type', sa.String(length=32), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('diagnosis_step_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_diagnosis_step_id'), 'tasks', ['diagnosis_step_id'], unique=True)
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=True)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_table('diagnosis_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_events_diagnosis_id'), 'diagnosis_events', ['diagnosis_id'], unique=False)
    op.create_table('diagnosis_evidence',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('evidence_role', sa.String(length=32), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=True),
    sa.Column('event_time_range_json', sa.JSON(), nullable=True),
    sa.Column('ingestion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query_or_probe', sa.String(length=256), nullable=False),
    sa.Column('raw_artifact_ref', sa.String(length=512), nullable=True),
    sa.Column('derived_artifact_ref', sa.String(length=512), nullable=True),
    sa.Column('derivation_version', sa.String(length=64), nullable=False),
    sa.Column('observed_value_json', sa.JSON(), nullable=True),
    sa.Column('baseline_value_json', sa.JSON(), nullable=True),
    sa.Column('anomaly_score_json', sa.JSON(), nullable=True),
    sa.Column('data_quality_json', sa.JSON(), nullable=True),
    sa.Column('integrity_hash', sa.String(length=80), nullable=False),
    sa.Column('claim_links_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_evidence_diagnosis_id'), 'diagnosis_evidence', ['diagnosis_id'], unique=False)
    op.create_table('diagnosis_node_runs',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_refs_json', sa.JSON(), nullable=True),
    sa.Column('output_refs_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('implementation_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'node_name', name='uq_diagnosis_node_name')
    )
    op.create_index(op.f('ix_diagnosis_node_runs_diagnosis_id'), 'diagnosis_node_runs', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_node_runs_node_name'), 'diagnosis_node_runs', ['node_name'], unique=False)
    op.create_table('diagnosis_probe_executions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('probe_id', sa.String(length=128), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_approval', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_probe_executions_diagnosis_id'), 'diagnosis_probe_executions', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_probe_executions_task_id'), 'diagnosis_probe_executions', ['task_id'], unique=False)
    op.create_table('diagnosis_runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('validated', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_runs_task_id'), 'diagnosis_runs', ['task_id'], unique=False)
    op.create_table('task_status_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_events_task_id'), 'task_status_events', ['task_id'], unique=False)
    op.create_table('diagnosis_reports',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('ranked_causes_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('not_enough_evidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_reports_diagnosis_id'), 'diagnosis_reports', ['diagnosis_id'], unique=False)
    op.create_table('diagnosis_task_outbox',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('step_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_sessions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['diagnosis_probe_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id')
    )
    op.create_index(op.f('ix_diagnosis_task_outbox_diagnosis_id'), 'diagnosis_task_outbox', ['diagnosis_id'], unique=False)
    op.create_table('diagnosis_tool_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_tool_results_diagnosis_id'), 'diagnosis_tool_results', ['diagnosis_id'], unique=False)
    op.create_table('rca_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('predicted_cause_id', sa.String(length=128), nullable=False),
    sa.Column('feedback_label', sa.String(length=32), nullable=False),
    sa.Column('corrected_cause_id', sa.String(length=128), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_feedback_diagnosis_id'), 'rca_feedback', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_rca_feedback_task_id'), 'rca_feedback', ['task_id'], unique=False)
    op.create_table('repair_plans',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=128), nullable=False),
    sa.Column('cause_id', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('executed_actions_json', sa.JSON(), nullable=True),
    sa.Column('requires_user_confirm', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_plans_diagnosis_id'), 'repair_plans', ['diagnosis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_plans_diagnosis_id'), table_name='repair_plans')
    op.drop_table('repair_plans')
    op.drop_index(op.f('ix_rca_feedback_task_id'), table_name='rca_feedback')
    op.drop_index(op.f('ix_rca_feedback_diagnosis_id'), table_name='rca_feedback')
    op.drop_table('rca_feedback')
    op.drop_index(op.f('ix_diagnosis_tool_results_diagnosis_id'), table_name='diagnosis_tool_results')
    op.drop_table('diagnosis_tool_results')
    op.drop_index(op.f('ix_diagnosis_task_outbox_diagnosis_id'), table_name='diagnosis_task_outbox')
    op.drop_table('diagnosis_task_outbox')
    op.drop_index(op.f('ix_diagnosis_reports_diagnosis_id'), table_name='diagnosis_reports')
    op.drop_table('diagnosis_reports')
    op.drop_index(op.f('ix_task_status_events_task_id'), table_name='task_status_events')
    op.drop_table('task_status_events')
    op.drop_index(op.f('ix_diagnosis_runs_task_id'), table_name='diagnosis_runs')
    op.drop_table('diagnosis_runs')
    op.drop_index(op.f('ix_diagnosis_probe_executions_task_id'), table_name='diagnosis_probe_executions')
    op.drop_index(op.f('ix_diagnosis_probe_executions_diagnosis_id'), table_name='diagnosis_probe_executions')
    op.drop_table('diagnosis_probe_executions')
    op.drop_index(op.f('ix_diagnosis_node_runs_node_name'), table_name='diagnosis_node_runs')
    op.drop_index(op.f('ix_diagnosis_node_runs_diagnosis_id'), table_name='diagnosis_node_runs')
    op.drop_table('diagnosis_node_runs')
    op.drop_index(op.f('ix_diagnosis_evidence_diagnosis_id'), table_name='diagnosis_evidence')
    op.drop_table('diagnosis_evidence')
    op.drop_index(op.f('ix_diagnosis_events_diagnosis_id'), table_name='diagnosis_events')
    op.drop_table('diagnosis_events')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_diagnosis_step_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_diagnosis_sessions_topology_snapshot_id'), table_name='diagnosis_sessions')
    op.drop_table('diagnosis_sessions')
    op.drop_index(op.f('ix_agent_metric_snapshots_agent_id'), table_name='agent_metric_snapshots')
    op.drop_table('agent_metric_snapshots')
    op.drop_table('topology_snapshots')
    op.drop_table('rca_feedback_weights')
    op.drop_table('audit_logs')
    op.drop_table('agents')
    # ### end Alembic commands ###
