#!/usr/bin/env python3
"""Generate the C0 implementation baseline from executable probes.

The generated state and command logs live under ``reports/implementation``
and are intentionally ignored by Git.  The versioned JSON Schema lives under
``reports/schemas``.  PASS values are derived only from subprocess exit codes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import shutil
import socket
import ssl
import subprocess
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = ROOT / "reports" / "implementation"
LOG_DIR = REPORT_DIR / "logs"
STATE_PATH = REPORT_DIR / "ai-agent-runtime-state.json"


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def command(argv: list[str], *, cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            argv,
            cwd=str(cwd),
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except FileNotFoundError as exc:
        return subprocess.CompletedProcess(argv, 127, "", str(exc))


def output(proc: subprocess.CompletedProcess[str]) -> str:
    return "\n".join(part for part in (proc.stdout, proc.stderr) if part).strip()


def write_log(name: str, proc: subprocess.CompletedProcess[str]) -> str:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    path = LOG_DIR / f"{name}.log"
    rendered = "$ " + subprocess.list2cmdline(proc.args) + "\n" + output(proc) + "\n"
    path.write_text(rendered, encoding="utf-8")
    return path.relative_to(ROOT).as_posix()


def git_text(*args: str) -> str:
    proc = command(["git", *args])
    if proc.returncode:
        raise RuntimeError(output(proc) or f"git {' '.join(args)} failed")
    return proc.stdout.rstrip()


def worktree_state() -> tuple[str, list[str], str]:
    commit = git_text("rev-parse", "HEAD")
    porcelain = git_text("status", "--short", "--untracked-files=all")
    changed = [line[3:] for line in porcelain.splitlines() if len(line) > 3]
    fingerprint = hashlib.sha256(f"{commit}\n{porcelain}\n".encode("utf-8")).hexdigest()
    return commit, changed, fingerprint


def python_versions(python: str) -> list[str]:
    proc = command([python, "-c", "import platform,sys; print(platform.python_version()); print(sys.executable)"])
    lines = [line.strip() for line in proc.stdout.splitlines() if line.strip()]
    return [" | ".join(lines)] if proc.returncode == 0 and lines else [f"UNAVAILABLE: {output(proc)}"]


def lock_status() -> tuple[str, list[str]]:
    uv_lock = ROOT / "uv.lock"
    requirements = ROOT / "requirements.lock"
    if not uv_lock.is_file() and not requirements.is_file():
        return "MISSING", ["neither uv.lock nor requirements.lock exists"]
    reasons: list[str] = []
    if not uv_lock.is_file():
        reasons.append("uv.lock is missing")
    if requirements.is_file():
        lock_text = requirements.read_text(encoding="utf-8")
        if re.search(r"(?m)^-e\s+git\+", lock_text):
            reasons.append("requirements.lock contains an editable Git dependency")
        if "autogenerated by uv" not in lock_text.lower():
            reasons.append("requirements.lock does not declare a reproducible generation command")
    uv = shutil.which("uv")
    if uv is None:
        reasons.append("uv is unavailable; lock freshness cannot be checked")
    elif uv_lock.is_file():
        lock_check = command([uv, "lock", "--check"])
        if lock_check.returncode:
            reasons.append("uv lock --check reports a stale or invalid lock")
    return ("INVALID", reasons) if reasons else ("VALID", [])


def architecture_violations() -> list[str]:
    violations: list[str] = []
    main = ROOT / "server" / "app" / "main.py"
    main_text = main.read_text(encoding="utf-8")
    line_count = len(main_text.splitlines())
    if line_count > 100:
        violations.append(f"server/app/main.py has {line_count} lines (target <= 100)")
    star_count = len(re.findall(r"(?m)^from\s+\S+\s+import\s+\*(?:\s*#.*)?$", main_text))
    if star_count:
        violations.append(f"server/app/main.py contains {star_count} star imports")
    route_imports = 0
    for path in (ROOT / "server" / "app").rglob("*.py"):
        normalized = path.as_posix()
        if "/routes/" not in normalized and path.name != "routes.py":
            continue
        text = path.read_text(encoding="utf-8")
        route_imports += len(re.findall(r"(?m)^(?:from|import)\s+server\.app\.main\b", text))
    if route_imports:
        violations.append(f"route modules import server.app.main {route_imports} times")
    if (ROOT / "server" / "app" / "models.py").exists() and (ROOT / "server" / "app" / "models").is_dir():
        violations.append("server/app/models.py and server/app/models/ both exist")
    if not (ROOT / ".gitattributes").is_file():
        violations.append(".gitattributes is missing; content-addressed line endings are not fixed")
    return violations


def summary(status: str = "NOT_RUN") -> dict[str, Any]:
    return {"status": status, "exit_code": None, "passed": 0, "failed": 0, "errors": 0, "skipped": 0}


def parse_count(pattern: str, text: str) -> int:
    matches = re.findall(pattern, text, flags=re.IGNORECASE | re.MULTILINE)
    return int(matches[-1]) if matches else 0


def test_summary(proc: subprocess.CompletedProcess[str], log: str, flavor: str) -> dict[str, Any]:
    text = output(proc)
    result = summary("PASS" if proc.returncode == 0 else "FAIL")
    result.update({"exit_code": proc.returncode, "log": log})
    if flavor == "pytest":
        result["passed"] = parse_count(r"(\d+)\s+passed", text)
        result["failed"] = parse_count(r"(\d+)\s+failed", text)
        result["errors"] = parse_count(r"(\d+)\s+errors?", text)
        result["skipped"] = parse_count(r"(\d+)\s+skipped", text)
    elif flavor == "node":
        # Node's TAP prefix may be rendered as mojibake by a Windows console;
        # match the stable ASCII summary tokens instead of anchoring at column 0.
        result["passed"] = parse_count(r"\bpass[ \t]+(\d+)", text)
        result["failed"] = parse_count(r"\bfail[ \t]+(\d+)", text)
        result["skipped"] = parse_count(r"\bskipped[ \t]+(\d+)", text)
    else:
        result["passed"] = parse_count(r"Tests\s+(\d+)\s+passed", text)
        result["failed"] = parse_count(r"Tests\s+(\d+)\s+failed", text)
        result["skipped"] = parse_count(r"Tests\s+(\d+)\s+skipped", text)
    return result


def run_and_record(name: str, argv: list[str], *, cwd: Path = ROOT) -> tuple[subprocess.CompletedProcess[str], dict[str, Any]]:
    proc = command(argv, cwd=cwd)
    log = write_log(name, proc)
    return proc, {"status": "PASS" if proc.returncode == 0 else "FAIL", "exit_code": proc.returncode, "log": log}


def probe_tcp(host: str, port: int) -> bool:
    try:
        with socket.create_connection((host, port), timeout=3):
            return True
    except OSError:
        return False


def probe_http(url: str) -> dict[str, Any]:
    context = ssl._create_unverified_context()  # Lab endpoint uses a private certificate.
    try:
        with urllib.request.urlopen(url, timeout=8, context=context) as response:
            return {"status": response.status, "ready": 200 <= response.status < 300}
    except urllib.error.HTTPError as exc:
        return {"status": exc.code, "ready": False}
    except Exception as exc:  # noqa: BLE001 - probe failures belong in the report.
        return {"status": None, "ready": False, "error": type(exc).__name__}


def derive_next_action(report: dict[str, Any]) -> str:
    if report["dependency_lock_status"] != "VALID":
        return "replace the invalid Python lock with a cross-platform lock, install it in an isolated Python 3.9 environment, then rerun C0"
    if report["python_test_summary"]["status"] != "PASS":
        return "fix the first reproducible Python gate failure, then rerun the complete Python gate"
    if report.get("checks", {}).get("ruff", {}).get("status") == "FAIL":
        return "fix the Ruff failure and rerun the Python gate"
    if report["migration_check"] != "PASS":
        return "repair the migration gate and rerun it against an empty database"
    if report["sidecar_test_summary"]["status"] != "PASS" or report["web_test_summary"]["status"] != "PASS":
        return "fix the failing Node gate and rerun Sidecar and Web tests"
    if any(
        report.get("checks", {}).get(name, {}).get("status") == "FAIL"
        for name in ("sidecar_audit", "web_audit", "web_lint", "web_build")
    ):
        return "fix the failing Node audit/lint/build gate and rerun the Node gate"
    if report["known_architecture_violations"]:
        if report["known_architecture_violations"] == [
            "server/app/models.py and server/app/models/ both exist",
        ]:
            return "continue C2 by eliminating the dual model source and making UoW boundaries explicit"
        return "continue C1 by migrating the next legacy route and eliminating bootstrap imports"
    return "run the C0 matrix on Linux and Windows before promoting to LOCAL_GREEN"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--run-tests", action="store_true")
    parser.add_argument("--probe-vm", action="store_true")
    parser.add_argument("--output", type=Path, default=STATE_PATH)
    args = parser.parse_args()

    commit, changed, fingerprint = worktree_state()
    node = command(["node", "--version"])
    heads = command([args.python, "-m", "alembic", "heads"])
    lock, lock_reasons = lock_status()
    proto, proto_check = run_and_record("compile-proto", [args.python, "scripts/compile_proto.py"])
    migration, migration_check = run_and_record("migration-check", [args.python, "scripts/check_migrations.py"])

    report: dict[str, Any] = {
        "schema_version": "implementation-baseline.v1",
        "generated_at": utcnow(),
        "platform": {"system": platform.system(), "release": platform.release(), "machine": platform.machine()},
        "base_commit": commit,
        "worktree_clean": not changed,
        "worktree_fingerprint": fingerprint,
        "changed_files": changed,
        "python_versions": python_versions(args.python),
        "node_version": node.stdout.strip() if node.returncode == 0 else "UNAVAILABLE",
        "alembic_heads": [line.strip() for line in heads.stdout.splitlines() if line.strip()],
        "dependency_lock_status": lock,
        "dependency_lock_reasons": lock_reasons,
        "protobuf_status": "READY" if proto.returncode == 0 else "NEEDS_GENERATION",
        "python_test_summary": summary(),
        "sidecar_test_summary": summary(),
        "web_test_summary": summary(),
        "migration_check": "PASS" if migration.returncode == 0 else "FAIL",
        "known_architecture_violations": architecture_violations(),
        "checks": {"compile_proto": proto_check, "migration": migration_check},
        "current_gate": "C0",
        "next_action": "pending probe completion",
    }

    npm = "npm.cmd" if os.name == "nt" else "npm"
    if args.run_tests:
        ruff, ruff_check = run_and_record("ruff", [args.python, "-m", "ruff", "check", "server", "agent", "analyzer"])
        pytest, _ = run_and_record("pytest", [args.python, "-m", "pytest", "-q"])
        sidecar, _ = run_and_record("sidecar-test", [npm, "test"], cwd=ROOT / "agent_runtime" / "pi-sidecar")
        _, sidecar_audit = run_and_record(
            "sidecar-audit", [npm, "audit", "--omit=dev"], cwd=ROOT / "agent_runtime" / "pi-sidecar"
        )
        web_test, _ = run_and_record("web-test", [npm, "test", "--", "--run"], cwd=ROOT / "web")
        _, web_audit = run_and_record("web-audit", [npm, "run", "audit:prod"], cwd=ROOT / "web")
        web_lint, lint_check = run_and_record("web-lint", [npm, "run", "lint"], cwd=ROOT / "web")
        web_build, build_check = run_and_record("web-build", [npm, "run", "build"], cwd=ROOT / "web")
        report["python_test_summary"] = test_summary(pytest, "reports/implementation/logs/pytest.log", "pytest")
        report["sidecar_test_summary"] = test_summary(sidecar, "reports/implementation/logs/sidecar-test.log", "node")
        report["web_test_summary"] = test_summary(web_test, "reports/implementation/logs/web-test.log", "vitest")
        report["checks"].update({
            "ruff": ruff_check,
            "sidecar_audit": sidecar_audit,
            "web_audit": web_audit,
            "web_lint": lint_check,
            "web_build": build_check,
        })

    if args.probe_vm:
        control = "192.168.10.10"
        report["service_status"] = {
            "ssh": {host: probe_tcp(host, 22) for host in (control, "192.168.10.11", "192.168.10.12")},
            "control_livez": probe_http(f"https://{control}/api/livez"),
            "control_readyz": probe_http(f"https://{control}/api/readyz"),
        }

    commit, changed, fingerprint = worktree_state()
    report.update({
        "generated_at": utcnow(),
        "base_commit": commit,
        "worktree_clean": not changed,
        "worktree_fingerprint": fingerprint,
        "changed_files": changed,
    })
    if args.run_tests and all(
        report[key]["status"] == "PASS"
        for key in ("python_test_summary", "sidecar_test_summary", "web_test_summary")
    ) and all(
        report["checks"].get(name, {}).get("status") == "PASS"
        for name in (
            "compile_proto",
            "migration",
            "ruff",
            "sidecar_audit",
            "web_audit",
            "web_lint",
            "web_build",
        )
    ):
        c1_blockers = (
            "server/app/main.py has",
            "server/app/main.py contains",
            "route modules import server.app.main",
        )
        report["current_gate"] = (
            "C1"
            if any(
                violation.startswith(c1_blockers)
                for violation in report["known_architecture_violations"]
            )
            else "C2"
        )
    report["next_action"] = derive_next_action(report)
    schema_check: dict[str, Any]
    try:
        import jsonschema
    except ImportError:
        schema_check = {"status": "NOT_RUN", "reason": "jsonschema is not installed"}
    else:
        schema_path = ROOT / "reports" / "schemas" / "implementation-baseline.schema.json"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        jsonschema.validate(report, schema)
        schema_check = {"status": "PASS", "schema": schema_path.relative_to(ROOT).as_posix()}
    report["checks"]["schema"] = schema_check
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    required_checks = ("compile_proto", "migration")
    if args.run_tests:
        required_checks += (
            "ruff", "sidecar_audit", "web_audit", "web_lint", "web_build", "schema",
        )
    checks_pass = (
        report["dependency_lock_status"] == "VALID"
        and report["protobuf_status"] == "READY"
        and report["migration_check"] == "PASS"
        and all(report["checks"].get(name, {}).get("status") == "PASS" for name in required_checks)
        and (not args.run_tests or all(
            report[key]["status"] == "PASS"
            for key in ("python_test_summary", "sidecar_test_summary", "web_test_summary")
        ))
    )
    return 0 if checks_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
